### ISSUE TITLE
Anos bissextos 

### ISSUE THREAD

**Issue by thiagooqueiroz** [hgees/deckseducativos#10]
Na hora de receber a data , precisamos diferenciar os anos bissextos

**Comment by aronsales** [comment]
Também devemos diferenciar a quantidade de dias em um mês, podendo um mês ter de 28 a 31 dias.

**Comment by wagner-lucas** [comment]
Isso, acho que devemos fazer funções aparte para poder ficar verificando se o dia e o mês não ultrapassa o máximo.

**Comment by alessonrenato** [comment]
criei uma funcao pra bissexto  no comit 6a4680c0d5c10fc566cf9e02707eeae28e1e0999

**Comment by alessonrenato** [comment]
resolvido no na issue #11
