### ISSUE TITLE
Milestone 1.0

### ISSUE THREAD

**Issue by alessonrenato** [hgees/deckseducativos#12]
Caros, a milestone v1.0 já pode ser fechada?

**Comment by iWarhead** [comment]
Creio que já fizemos até mais do que era previsto para esta milestone. Então pode sim.

**Comment by alessonrenato** [comment]
Fica pra 2.0 recuperar/gravar no arquivo e exibir as palavras

**Comment by wagner-lucas** [comment]
Pode, algumas funções estava sem protótipo, mas eu ja enviei e como a fila ja esta implementada concordo em fechar.

**Comment by aronsales** [comment]
Cumprimos os objetivos previstos pra esta milestone. Pode sim.
