### ISSUE TITLE
Função 'help' diferente da 'inicio' ? 

### ISSUE THREAD

**Issue by aronsales** [hgees/deckseducativos#13]
Seria preciso uma nova função para ''ensinar'' o usuário a jogar? Na função ''inicio'' se encontra um breve resumo do programa, sem instruções ''práticas'', gostaria de saber dos meus companheiros de grupo, se seria necessário a criação de uma nova função, ou somente um acrescer a função ''inicio'' com estas instruções ?

**Comment by iWarhead** [comment]
Creio que na função início estejam todas as instruções necessárias. Consegue pensar em algo que poderia ser adicionado?

**Comment by hgees** [comment]
Concordo com Arthur, não vejo motivo para fazer outra função.

**Comment by aronsales** [comment]
Visto desse ponto, também concordo com todos que comentaram aqui, questão solucionada.
