### ISSUE TITLE
Arquivo

### ISSUE THREAD

**Issue by wagner-lucas** [hgees/deckseducativos#14]
Amigos eu comecei o uso de arquivo na função principal, coloquei para abrir e fazer uma leitura dos arquivo na primeira execução, caso ja exista ler e depois fecha, caso nao, ele cria e depois fecha . eb458106fe4c7c6c0aa999b502484e4c15e76a6c

**Comment by hgees** [comment]
Muito bom... isso acaba nos protegendo do usuário apagar o arquivo
