### ISSUE TITLE
Gravando arquivo

### ISSUE THREAD

**Issue by wagner-lucas** [hgees/deckseducativos#15]
Adicionei um bloco de código que verifica e grava os arquivo. No caso do arquivo de filaderevisão ele grava a palavra,a data, o agendamento e a media. No commit 9495875c79c73fde35e9c97904b658aa0d09b138 e 9495875c79c73fde35e9c97904b658aa0d09b138 .

**Comment by alessonrenato** [comment]
ok,vou fechar a issue pra lançar a versão 2.0
