### ISSUE TITLE
Bug na recuperação de fila.

### ISSUE THREAD

**Issue by alessonrenato** [hgees/deckseducativos#17]
Galera existe um bug que o faz o programa ficar em loop infinito na recuperação da fila, desconfio que seja na função fscanf da linha 90. Farei alguns testes pra confirmar

**Comment by tonyfrance** [comment]
confirmou se era isso mesmo alesson?

**Comment by alessonrenato** [comment]
sim. to vendo uma forma de corrigir.

**Comment by iWarhead** [comment]
Corrigi o bug no commit 75b33e06f91c116ec085aaeaae4f16884231176d
Tinha um ponto e virgula no final do while. E a posição dos "&" estava errada. Tambem fiz uma modificação pra evitar que o parâmetro "prox" pegue lixo.
