### ISSUE TITLE
Certificado

### ISSUE THREAD

**Issue by wagner-lucas** [hgees/deckseducativos#18]
Como estamos corrigindo apenas alguns bugs no programa, acho que ja podemos pensar no certificado que vamos imprimir para o usuário quando ele tiver nota 5 em todas as cartas. Então deixem suas ideias aqui para podermos implementar da melhor maneira possível esse certificado.

**Comment by aronsales** [comment]
Seria interessante ter no certificado:
Nome completo 
Data de início 
Data de conclusão 
Carga horária
Número de cards aprendidos
O tema dos cards

**Comment by wagner-lucas** [comment]
a data de inicio e conclusão da para pegar e com isso fazer a carga horária, ai no caso do nome íamos ter que perguntar ao usuário quando ele tivesse nota 5 em todos os cards?

**Comment by aronsales** [comment]
Sim, ao fim do programa perguntariamos o nome completo do usuário, para emissão do certificado

**Comment by hgees** [comment]
mas esse certificado seria apenas impresso na tela ao final do programa?? creio que ficaria melhor se ele criasse um arquivo com os dados do usuario

**Comment by aronsales** [comment]
Ou poderia guardar a data de início em uma variável estática, e quando a média do usuário for maior/igual a 4,5 chama a funcao certificado, que recolherá a data atual do sistema e perguntará o nome do usuário.

**Comment by thiagooqueiroz** [comment]
Mas tem q ser depois das 1500 cartas , essa media , salvando em um arquivo.
Contendo alem do nome dele , data de começo , fim de aprendizado e tema , dizendo com qual media ele terminou(4.5<media<5)

**Comment by tonyfrance** [comment]
Como Hericles disse, seria bom criar um arquivo quando terminasse os 1500 cards, onde o usuario possa baixar para sua maquina permitindo assim imprimir caso ele queira.

**Comment by aronsales** [comment]
Um esqueleto da função foi colocado por mim, peço a ajuda de vocês para a otimização da mesma.

**Comment by iWarhead** [comment]
O arquivo precisa ser criado já na primeira execução, com a data inicial, já que colocaremos a carga horária no certificado.

**Comment by aronsales** [comment]
Arquivo criado na primeira execução e guardará a data inicial do programa, e a carga horaria.
Função certificado criada.
