### ISSUE TITLE
Carga horaria

### ISSUE THREAD

**Issue by aronsales** [hgees/deckseducativos#20]
Gostaria da ajuda de vocês no seguinte problema, a carga horaria do certificado está saindo no formato AAAAMMDD, como podemos solucionar este problema ?

**Comment by tonyfrance** [comment]
podemos usar a divisão para fragmentar o numero  e colocar as variaveis como tipo int,  assim separamos ano mes e dia

**Comment by aronsales** [comment]
Com este pedaço de código consigo fazer o que tu tais querendo dizer Tony!

`ano=cargahoraria/10000;`
`mes=(cargahoraria-(ano*10000))/100;`
`dia=(cargahoraria-(ano*10000+mes*100));`

Considero este problema resolvido !

**Comment by tonyfrance** [comment]
aron eu fiz o dia assim
`dia=cargahoraria%100;`

assim ele vai imprimir os decimais que sao os dias

**Comment by aronsales** [comment]
Pode ser também Tony ! 
Fica até mais prático e enxuto o código
