### ISSUE TITLE
Media de palavra soreteada

### ISSUE THREAD

**Issue by wagner-lucas** [hgees/deckseducativos#23]
Na primeira vez que a palavra é sorteada e o usuario da uma nota, entao a nota vai ser a propria media. Nesse caso não precisa calcular a media, a condição que eu adicionei é justamente isso. 09faa176fc6587e4a8d718b69ff60445a184a3eb

**Comment by hgees** [comment]
Muito bom Wagner, estava tendo problemas com isso
