### ISSUE TITLE
Gravar o certificado no arquivo ''certificado.txt"

### ISSUE THREAD

**Issue by aronsales** [hgees/deckseducativos#24]
Gostaria da ajuda de vocês pra saber se seria uma boa ideia gravar o certificado em um arquivo, para se o usuário quiser, imprimir posteriormente.

**Comment by hgees** [comment]
Muito boa idéia... eu já até tinha comentado algo assim mas não implementei

**Comment by alessonrenato** [comment]
Implementei a função verificaNota no commit 
o programa agora verifica se o desempenho foi atingido e imprime o certificado
