### ISSUE TITLE
Master Atualizado

### ISSUE THREAD

**Issue by iWarhead** [hgees/deckseducativos#25]
Caros, o programa já chegou onde queríamos, então atualizei o ramo master já. Estou só esperando a confirmação de vocês pra mandar o release v3.0.

**Comment by alessonrenato** [comment]
De minha parte está tudo ok.

**Comment by wagner-lucas** [comment]
Por mim está tudo certo, pode mandar.

**Comment by tonyfrance** [comment]
ok

**Comment by hgees** [comment]
Acabei de rodar uma última vez o programa e ele está de acordo com o esperado. Por mim já pode atualizar o master.

**Comment by hgees** [comment]
Correção, pode colocar a tag.

**Comment by aronsales** [comment]
Por mim está tudo certo, trabalho encerrado.

**Comment by iWarhead** [comment]
Tag lançada. Fecharei a issue e a última milestone.
Bom Trabalho.

**Comment by alessonrenato** [comment]
lembrem de mover a pasta para trabalhos
