### ISSUE TITLE
Funcão Randomica

### ISSUE THREAD

**Issue by alessonrenato** [hgees/deckseducativos#3]
Caros, no ônibus encontrei uma solução genérica para a função de randomizar as palavras usando vetor variável.

Podemos criar um vetor inteiro variável de 0 a 1499 e colocar em suas posições o número 0 a 1499. Ao sortear algum numero, a função troca a ultima posição do vetor pelo numero sorteado e realocar um novo vetor com x-1 posições.

o legal é que isso ainda ajudaria a embaralhar mais os números já que o RND = %n não necessariamente será o numero escolhido.

**Comment by hgees** [comment]
Criei uma função que faz a tua ideia. Issue fechada.

**Comment by alessonrenato** [comment]
Dei uma melhorada na função usando vetor variável, agora o número sorteado será retirado da memória.
