### ISSUE TITLE
Funcao data

### ISSUE THREAD

**Issue by wagner-lucas** [hgees/deckseducativos#4]

**Comment by wagner-lucas** [comment]
Criei uma função que pega a data do sistema e que retorna ano,dia e mes em um formato unico, ex:´´´20160416´´´ ,  desse modo podemos comparar as datas na lista. Porem não estou pegando a hora, vcs acham necessário ?.

**Comment by hgees** [comment]
Muito bom!! porém não vejo utilidade para a hora no programa

**Comment by aronsales** [comment]
A hora do programa não será necessária, pois independente da hora, os remarcamentos serão efetuados somente pela data, isto é, pela quantidade de dias subsequentes.
