### ISSUE TITLE
Necessidade de uma função 'help'

### ISSUE THREAD

**Issue by aronsales** [hgees/deckseducativos#6]
Gostaria de saber de vocês, se seria útil a criação de uma função 'help', pra se o usuário tiver duvidas ao longo do funcionamento, ele poder ter um breve resumo das regras/funcionamento.

**Comment by hgees** [comment]
acho bastante válido pois é algo simples que pode saciar duvidas do usuario

**Comment by thiagooqueiroz** [comment]
É valido man , quando o usuario precisar , ter um "menu" em que ele possa tirar suas duvidas , ou colocar qnd começar o programa

**Comment by thiagooqueiroz** [comment]
É valido , quando o usuario precisar , ter um "menu" em que ele possa tirar suas duvidas , ou colocar qnd começar o programa

**Comment by iWarhead** [comment]
Podemos fazer uma função para que sempre que o usuário digitar uma certa tecla, imprimirá um menu no qual ele pode navegar.

**Comment by wagner-lucas** [comment]
concordo, pois assim diminui o numero de coisa na tela, pois so vai aparecer se o usuário quiser.

**Comment by iWarhead** [comment]
Modifiquei a função inicio, agora sempre que o usuário quiser ver as instruções novamente, basta apertar a tecla <h>.
