### ISSUE TITLE
Ajuda na funcao imprime

### ISSUE THREAD

**Issue by thiagooqueiroz** [hgees/deckseducativos#7]
Pessoal acrescentei a funcao imprime,
imprimindo apenas uma linha , mas ainda tem q haver a separação por ": :" ,
gostaria de algumas ideias  para melhorar o codigo

**Comment by hgees** [comment]
percebi que seu codigo imprime a string toda quando deveria imprimir separadamente antes e depois dos "::" .
creio que a função strtok resolverá isso.
